### ISSUE TITLE
Just a friendly suggestion. 

### ISSUE THREAD

**Issue by xrviv** [ethicnology/dispute#10]
I think I sort of get the gist for this - a debate platform? It would be helpful to have a short and descriptive "about" the app section.

**Comment by ethicnology** [comment]
Hi @xrviv thanks for the interest and sorry for the delay, i'm not developing this app since it would take too much time (I also seek freelance mission to live) considering I'm also maintaining the library [nostr](https://github.com/ethicnology/dart-nostr) which let others developers to develop better apps than me (I'm not a front-end fellow).

**Comment by xrviv** [comment]
Alright. :) thanks for replying.

**Comment by xrviv** [comment]
Mmmm, we could pop it at chatgpt and see if it could code it,,,
